### ISSUE TITLE
`Shortcut keys` don't work anymore

### ISSUE THREAD

**Issue by MarekLew** [Grabacr07/SylphyHorn#32]
After windows 10 update in my version SymphyHorn 2.5 from Windows Story, keys to switch/pined windows not work.

### System
 Version	10.0.17134 Compile 17134
 SymphyHorn 2.5

**Comment by Roy-Orbison** [comment]
I have the same thing after I updated Windows yesterday to version 1803, build 17134.165.

**Comment by possum-enjoyer** [comment]
I too have a problem, that i can't use the keys to switch windows between desktops

**Comment by R-OLE** [comment]
Just happened to me too, after recent MS updates.
Still running Win10 Build 16299. 
Seems hotfixes have disabled mechanism by which this particular app uses these hotkeys?
I checked and (OLD) Free & Open Source version of [zVD](https://github.com/jan-glx/zVirtualDesktop)  still can use these hotkeys to do these functions just fine.
I **prefer** your code: lighter, simpler, uses app store, supported open source (...I hope...).

**Comment by MarekLew** [comment]
Work for SymphyHorn 3.0
